import { BrowserWindow } from 'electron'
import { join } from 'path'
import { app } from 'electron'
import { existsSync, mkdirSync, readFileSync } from 'fs'

export interface LoginPlatform {
  /** 唯一 key，同时用作 cookie 文件名与 Electron session 分区名 */
  id: string
  label: string
  /** 命中任意一个即认为该链接属于本平台 */
  hosts: string[]
  /** 登录页地址，会在登录窗口中打开 */
  loginUrl: string
  /** 判定「已登录」的 Cookie 名，任一存在即认为登录成功 */
  loginCookies: string[]
  /** 是否已有可用的 extractor（yt-dlp 内置或本项目插件提供） */
  hasExtractor: boolean
  /** 需要登录才能取到信息 */
  requireLogin: boolean
  /** 已知限制，展示在设置面板里 */
  note?: string
}

export const NETSCAPE_COOKIE_HEADER = `# Netscape HTTP Cookie File
# Generated by doudou-video-downloader.  Do not edit.
`

export const LOGIN_PLATFORMS: LoginPlatform[] = [
  {
    id: 'douyin',
    label: '抖音',
    hosts: ['douyin.com'],
    loginUrl: 'https://www.douyin.com/',
    loginCookies: ['sessionid', 'sessionid_ss'],
    hasExtractor: true,
    requireLogin: true
  },
  {
    id: 'kuaishou',
    label: '快手',
    hosts: ['kuaishou.com', 'gifshow.com', 'chenzhongtech.com'],
    loginUrl: 'https://www.kuaishou.com/',
    loginCookies: ['passToken', 'kuaishou.web.cp.api_st'],
    hasExtractor: true,
    requireLogin: true,
    note: '受快手风控限制，被判风险的 IP 会收到验证码要求（code 400002）。换网络环境可提高成功率。'
  },
  {
    id: 'weixinchannels',
    label: '视频号',
    // 分享链接是 weixin.qq.com/sph/<id>，会 302 到 channels.weixin.qq.com 的预览页
    hosts: ['weixin.qq.com', 'channels.weixin.qq.com'],
    loginUrl: 'https://channels.weixin.qq.com/platform',
    loginCookies: ['wxuin', 'wxsid'],
    hasExtractor: true,
    requireLogin: true,
    note: '视频号预览接口只返回封面和文案，不下发视频流地址，因此只能识别链接、无法下载。'
  }
]



function hostOf(url: string): string | null {
  try {
    return new URL(url).hostname.replace(/^www\./, '').toLowerCase()
  } catch {
    return null
  }
}

export function getPlatformByUrl(url: string): LoginPlatform | null {
  const host = hostOf(url)
  if (!host) return null
  return (
    LOGIN_PLATFORMS.find((p) => p.hosts.some((h) => host === h || host.endsWith(`.${h}`))) || null
  )
}

export function getPlatformById(id: string): LoginPlatform | null {
  return LOGIN_PLATFORMS.find((p) => p.id === id) || null
}

/** 独立分区，登录后的 Cookie 持久化到磁盘，重启应用无需重新登录 */
export function partitionFor(platformId: string): string {
  return `persist:doudou-${platformId}`
}

export function getCookiesDir(): string {
  const dir = join(app.getPath('userData'), 'cookies')
  if (!existsSync(dir)) mkdirSync(dir, { recursive: true })
  return dir
}

export function getCookiesPath(platformId: string): string {
  return join(getCookiesDir(), `${platformId}.txt`)
}

interface CookieLine {
  domain: string
  name: string
  value: string
}

/** 读取已保存的 Netscape cookie 文件 */
function readCookieLines(platformId: string): CookieLine[] {
  const path = getCookiesPath(platformId)
  if (!existsSync(path)) return []
  let text = ''
  try {
    text = readFileSync(path, 'utf-8')
  } catch {
    return []
  }
  const out: CookieLine[] = []
  for (const raw of text.split('\n')) {
    const line = raw.trimEnd()
    if (!line) continue
    const body = line.startsWith('#HttpOnly_') ? line.slice('#HttpOnly_'.length) : line
    if (body.startsWith('#')) continue
    const parts = body.split('\t')
    if (parts.length < 7) continue
    out.push({ domain: parts[0], name: parts[5], value: parts.slice(6).join('\t') })
  }
  return out
}

export interface PlatformLoginState {
  id: string
  label: string
  hasExtractor: boolean
  requireLogin: boolean
  note?: string
  loginUrl: string
  cookiesPath: string
  cookieCount: number
  loggedIn: boolean
}

export function getPlatformLoginState(platform: LoginPlatform): PlatformLoginState {
  const lines = readCookieLines(platform.id)
  const names = new Set(lines.map((l) => l.name))
  const loggedIn = platform.loginCookies.some((n) => names.has(n))
  return {
    id: platform.id,
    label: platform.label,
    hasExtractor: platform.hasExtractor,
    requireLogin: platform.requireLogin,
    note: platform.note,
    loginUrl: platform.loginUrl,
    cookiesPath: getCookiesPath(platform.id),
    cookieCount: lines.length,
    loggedIn
  }
}

export function getAllPlatformLoginStates(): PlatformLoginState[] {
  return LOGIN_PLATFORMS.map(getPlatformLoginState)
}

/** 平台是否存在可用于 yt-dlp 的 cookie 文件（不需要真的登录成功） */
export function getUsableCookiesPath(platformId: string): string {
  const path = getCookiesPath(platformId)
  if (!existsSync(path)) return ''
  return readCookieLines(platformId).length > 0 ? path : ''
}

export function parentWindow(): BrowserWindow | null {
  return BrowserWindow.getAllWindows()[0] || null
}